### ISSUE TITLE
Grails 3 final tasks

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#1248]
- [x] Grails 3 dev environment setup documentation
- [x] Migrate MLOZ data to current ecodata
- [x] Sync hot fixes to grails 3 branch
- [x]  Prepare regression testing plan
- [x] Upgrade MLOZ server to ubuntu 18
- [x] Test using native mobile iOS
- [x] Test Android apps
- [x] Point mloz.ala.org.au > Upload sightings to BioCollect MLOZ project
- [x] Prepare bicollect-dev to biocollect-uat with own instance of ecodata

**Issues to fix before Grails 3 version can be released**
- [x] #1264 Terms of Use invalid link
- [x] #1219 Survey save without all mandatory fields fixed
- [x] #1185 Project finder - indexed string search not working
- [x] #1263 Works project sites don't load
- [x] #1268 Mobile apps grails 3 issues
- [x] add termsOfUseUrl config to Biocollects Ansible config
- [x] issue with redirecting URI parameter. The effect was adding localhost to response location parameter.
- [x] biocollect homepage returning internal server error e.g. https://biocollect-dev.ala.org.au/

**Issues to fix post-release** 
- [x] #1223 
- [x] #1220 
- [x] #1211 
- [x] #1186 
- [x] #1208 
- [x] #1214 
- [x] #1216
- [ ] #1262 Can't create activity in nrm works project

Works projects: 
https://biocollect.ala.org.au/nrmworks/project/index/6019d6ef-76cf-47a7-8635-6b7f8954746f

New BioCollect Prod Server:
aws-biocollect-mloz is now running Ubuntu 18.04
To install/use nginx, add this to the inventory ala_webserver="nginx"
Update role/playbooks/inventories to reflect the nginx change.

**Comment by temi** [comment]
#1262 is the only one left. It will be done in the future release. Closing ticket.
