### ISSUE TITLE
ACSA Hub development

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#560]
The Australian Citizen Science Association (ACSA) is engaging the ALA to develop a BioCollect project finder hub for ACSA to enable the discovery of all CS projects relevant to Australia and which Australians can participate in. This will involve the ability to register all kinds of CS projects including non-biodiversity and NRM related projects (eg. astronomy, social science, medical science, geology, etc.). They also want to be able to toggle to a view of all projects globally, regardless of relevance to Australia.

Most of the functionality to do this already exists in BioCollect, but some additions and configuration options need to be implemented to complete the functional requirements. These include:
- [ ] Add new science types to the CS project metadata page #566
- [ ] Add a 'bar' to use of biocollect data collection features for science types which are not specified as related to biodiversity. #565 
- [ ] Create a separate hub for ACSA, including skinning/styling as required. #561 
- [ ] Set-up new sub-domain (acsa.ala.org.au) and redirect to ASCA hub #574 
- [ ] Add toggle buttons to display all global projects or only those relevant to Australia and set default to Australia. #567

Priority sequence should be:
1.  #566 
2.  #565 
3.  #561 
4.  #574 
5.  #567
